[package]
name = "edar"
version = "0.1.0"
edition = "2024"
authors = ["darrkenn <darrkenn08@gmail.com>"]
description = "A tool to get an audio files' metadata easier"
readme = "README.md"
repository = "https://github.com/darrkenn/edar"
license = "MIT"
license-file = "LICENSE.md"

[dependencies]
