# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    cargo install cargo2junit
    RUSTC_BOOTSTRAP=1
    cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
  displayName: 'View file structure'

- task: PublishTestResults@2
  inputs: 
    testResultsFormat: 'JUnit'
    testResultsFiles: 'results.xml'
  condition: succeededOrFailed()
