trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: |
      cargo install cargo2junit
      RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
    displayName: "Run Tests"

  - task: PublishTestResults@2
    displayName: PUblish Test Results
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "results.xml"
    condition: succeededOrFailed()

  - script: |
      cargo package
      cargo publish --token $(cargoapi)
